name: ${project.artifactId}
version: ${project.version}
main: com.mcmiddleearth.entities.EntitiesPlugin
api-version: 1.16
depend: [ ProtocolLib ]
softdepend: [ WorldEdit ]
authors: [ Eriol_Eandur ]

commands:
  npc:
    description: manges fake players
    usage: /npc
  mob:
    description: manges fake mobs
    usage: /mob
  entity:
    description: manges fake entities
    usage: /entity
  animation:
    description: manges entity animations
    usage: /animation
  vspawn:
    description: manages virtual entities
    usage: /virtual spawn | kill | animate
  varmy:
    description: manages virtual entities
    usage: /virtual spawn | kill | animate
  vset:
    description: manages virtual entities
    usage: /virtual spawn | kill | animate
  vremove:
    description: manages virtual entities
    usage: /virtual spawn | kill | animate
  vtest:
    description: manages virtual entities
    usage: /virtual spawn | kill | animate
  vsay:
    description: manages virtual entities
    usage: /virtual spawn | kill | animate
  vload:
    description: manages virtual entities
    usage: /virtual spawn | kill | animate
  vsave:
    description: manages virtual entities
    usage: /virtual spawn | kill | animate
  vselect:
    description: manages virtual entities
    usage: /virtual spawn | kill | animate
  vfactory:
    description: manages virtual entities
    usage: /virtual spawn | kill | animate
  vanimate:
    description: manages virtual entities
    usage: /virtual spawn | kill | animate
  vserver:
    description: manages entities plugin
    usage: /entities reload | restart

permissions:
  mcmeentities.admin:
    description: allows to manage plugin
    default: op
  mcmeentities.user:
    description: allow to use plugin commands
    default: op
  mcmeentities.viewer:
    description: allow to see virtual entities
    default: op